# Generated by Django 4.2.1 on 2023-05-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('faculty', models.ManyToManyField(to='faculty.faculty')),
            ],
            options={
                'verbose_name': 'Stundets',
                'verbose_name_plural': 'Students',
                'db_table': 'Students',
            },
        ),
    ]
