# Generated by Django 4.2.1 on 2023-05-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_public_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine_Arts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'School of Fine Arts',
                'verbose_name_plural': 'School of Fine Arts',
                'db_table': 'School of Fine Arts',
            },
        ),
    ]
