# Generated by Django 4.2.1 on 2023-05-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_delete_education_delete_engineering_delete_fine_arts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'School of Engineering',
                'verbose_name_plural': 'School of Engineering',
                'db_table': 'School of Engineering',
            },
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Law School',
                'verbose_name_plural': 'Law School',
                'db_table': 'Law School',
            },
        ),
        migrations.CreateModel(
            name='Medical_School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Medical School',
                'verbose_name_plural': 'Medical School',
                'db_table': 'Medical School',
            },
        ),
    ]
