# Generated by Django 4.2.1 on 2023-05-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_And_Ethical_Issues_In_Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='social_and_ethical_issues_in_medicine_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Social And Ethical Issues In Medicine',
                'verbose_name_plural': 'Social And Ethical Issues In Medicine',
                'db_table': 'Social And Ethical Issues In Medicine',
            },
        ),
        migrations.CreateModel(
            name='Pharmacology_And_Therapeutics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='pharmacology_and_therapeutics_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Pharmacology And Therapeutics',
                'verbose_name_plural': 'Pharmacology And Therapeutics',
                'db_table': 'Pharmacology And Therapeutics',
            },
        ),
        migrations.CreateModel(
            name='Pathways_Mechanisms_And_Models_Of_Human_Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='pathways_mechanisms_and_models_of_human_disease_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Pathways, Mechanisms, And Models Of Human Disease',
                'verbose_name_plural': 'Pathways, Mechanisms, And Models Of Human Disease',
                'db_table': 'Pathways, Mechanisms, And Models Of Human Disease',
            },
        ),
        migrations.CreateModel(
            name='Medical_Biochemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='medical_biochemistry_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Medical Biochemistry',
                'verbose_name_plural': 'Medical Biochemistry',
                'db_table': 'Medical Biochemistry',
            },
        ),
        migrations.CreateModel(
            name='Immunology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='immunology_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Immunology',
                'verbose_name_plural': 'Immunology',
                'db_table': 'Immunology',
            },
        ),
        migrations.CreateModel(
            name='Human_Physiology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='human_physiology_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Human Physiology',
                'verbose_name_plural': 'Human Physiology',
                'db_table': 'Human Physiology',
            },
        ),
        migrations.CreateModel(
            name='Human_Anatomy_And_Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='human_anatomy_and_development_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Human Anatomy And Development',
                'verbose_name_plural': 'Human Anatomy And Development',
                'db_table': 'Human Anatomy And Development',
            },
        ),
        migrations.CreateModel(
            name='Genetics_And_Genomics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='genetics_and_genomics_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Genetics And Genomics',
                'verbose_name_plural': 'Genetics And Genomics',
                'db_table': 'Genetics And Genomics',
            },
        ),
    ]
