# Generated by Django 4.2.1 on 2023-05-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='torts_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Torts',
                'verbose_name_plural': 'Torts',
                'db_table': 'Torts',
            },
        ),
        migrations.CreateModel(
            name='Taxation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='taxation_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Taxation',
                'verbose_name_plural': 'Taxation',
                'db_table': 'Taxation',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='property_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Property',
                'db_table': 'Property',
            },
        ),
        migrations.CreateModel(
            name='Legislation_And_Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='legislation_and_regulation_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Legislation And Regulation',
                'verbose_name_plural': 'Legislation And Regulation',
                'db_table': 'Legislation And Regulation',
            },
        ),
        migrations.CreateModel(
            name='Legal_Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='legal_profession_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Legal Profession',
                'verbose_name_plural': 'Legal Profession',
                'db_table': 'Legal Profession',
            },
        ),
        migrations.CreateModel(
            name='Labor_Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='labor_law_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Labor Law',
                'verbose_name_plural': 'Labor Law',
                'db_table': 'Labor Law',
            },
        ),
        migrations.CreateModel(
            name='International_Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='international_law_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'International Law',
                'verbose_name_plural': 'International Law',
                'db_table': 'International Law',
            },
        ),
        migrations.CreateModel(
            name='Intellectual_Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='intellectual_property_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Intellectual Property',
                'verbose_name_plural': 'Intellectual Property',
                'db_table': 'Intellectual Property',
            },
        ),
        migrations.CreateModel(
            name='Family_Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='family_law_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Family Law',
                'verbose_name_plural': 'Family Law',
                'db_table': 'Family Law',
            },
        ),
        migrations.CreateModel(
            name='Environmental_Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='environmental_law_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Environmental Law',
                'verbose_name_plural': 'Environmental Law',
                'db_table': 'Environmental Law',
            },
        ),
        migrations.CreateModel(
            name='Criminal_Law_And_Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='criminal_law_and_procedure_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Criminal Law And Procedure',
                'verbose_name_plural': 'Criminal Law And Procedure',
                'db_table': 'Criminal Law And Procedure',
            },
        ),
        migrations.CreateModel(
            name='Corporate_Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='corporate_law_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Corporate Law',
                'verbose_name_plural': 'Corporate Law',
                'db_table': 'Corporate Law',
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='contracts_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Contracts',
                'verbose_name_plural': 'Contracts',
                'db_table': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='Constitutional_Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='constitutional_law_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Constitutional Law',
                'verbose_name_plural': 'Constitutional Law',
                'db_table': 'Constitutional Law',
            },
        ),
        migrations.CreateModel(
            name='Civil_Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='civil_procedure_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Civil Procedure',
                'verbose_name_plural': 'Civil Procedure',
                'db_table': 'Civil Procedure',
            },
        ),
    ]
