# Generated by Django 4.2.1 on 2023-05-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanical_Engineering_Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='mechanical_engineering_design_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Mechanical Engineering Design',
                'verbose_name_plural': 'Mechanical Engineering Design',
                'db_table': 'Mechanical Engineering Design',
            },
        ),
        migrations.CreateModel(
            name='Materials_Science_And_Engineering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='materials_science_and_engineering_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Materials Science And Engineering',
                'verbose_name_plural': 'Materials Science And Engineering',
                'db_table': 'Materials Science And Engineering',
            },
        ),
        migrations.CreateModel(
            name='Introduction_To_Solid_State_Chemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='introduction_to_solid_state_chemistry_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Introduction To Solid-State Chemistry',
                'verbose_name_plural': 'Introduction To Solid-State Chemistry',
                'db_table': 'Introduction To Solid-State Chemistry',
            },
        ),
        migrations.CreateModel(
            name='Introduction_To_Robotics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='introduction_to_robotics_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Introduction To Robotics',
                'verbose_name_plural': 'Introduction To Robotics',
                'db_table': 'Introduction To Robotics',
            },
        ),
        migrations.CreateModel(
            name='Introduction_To_Eecs_Via_Communication_Networks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='introduction_to_eecs_via_communication_networks_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Introduction To Eecs Via Communication Networks',
                'verbose_name_plural': 'Introduction To Eecs Via Communication Networks',
                'db_table': 'Introduction To Eecs Via Communication Networks',
            },
        ),
        migrations.CreateModel(
            name='Introduction_To_Computer_Science_And_Programming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='introduction_to_computer_science_and_programming_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Introduction To Computer Science And Programming',
                'verbose_name_plural': 'Introduction To Computer Science And Programming',
                'db_table': 'Introduction To Computer Science And Programming',
            },
        ),
        migrations.CreateModel(
            name='Introduction_To_Biological_Engineering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='introduction_to_biological_engineering_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Introduction To Biological Engineering',
                'verbose_name_plural': 'Introduction To Biological Engineering',
                'db_table': 'Introduction To Biological Engineering',
            },
        ),
        migrations.CreateModel(
            name='Introduction_To_Aerospace_And_Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='introduction_to_aerospace_and_design_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Introduction To Aerospace And Design',
                'verbose_name_plural': 'Introduction To Aerospace And Design',
                'db_table': 'Introduction To Aerospace And Design',
            },
        ),
        migrations.CreateModel(
            name='Digital_Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.CharField(max_length=5)),
                ('exam2', models.CharField(max_length=5)),
                ('exam3', models.CharField(max_length=5)),
                ('student_name', models.ManyToManyField(related_name='digital_electronics_students_name', to='students.students')),
            ],
            options={
                'verbose_name': 'Digital Electronics',
                'verbose_name_plural': 'Digital Electronics',
                'db_table': 'Digital Electronics',
            },
        ),
    ]
